# Generated by Django 3.0.5 on 2021-03-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=40)),
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=40)),
            ],
        ),
    ]
