# Generated by Django 3.0.5 on 2021-03-01 06:17

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=20, unique=True)),
                ('client_id', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=2083, unique=True)),
                ('token_endpoint', models.CharField(max_length=2083)),
                ('scope', jsonfield.fields.JSONField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=2048)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
