# Generated by Django 3.1.6 on 2021-03-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discord_user_info',
            name='users',
        ),
        migrations.AddField(
            model_name='discord_user_info',
            name='users',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reddit_user_info',
            name='users',
        ),
        migrations.AddField(
            model_name='reddit_user_info',
            name='users',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='spotify_user_info',
            name='users',
        ),
        migrations.AddField(
            model_name='spotify_user_info',
            name='users',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
