# Generated by Django 3.2 on 2021-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20210427_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify_user_info',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
