# Generated by Django 3.1.7 on 2021-04-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20210327_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditAPIInfo',
            fields=[
                ('apiinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.apiinfo')),
            ],
            bases=('integrations.apiinfo',),
        ),
        migrations.CreateModel(
            name='SpotifyAPIInfo',
            fields=[
                ('apiinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.apiinfo')),
            ],
            bases=('integrations.apiinfo',),
        ),
    ]
