# Generated by Django 3.0.5 on 2021-03-04 19:41

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('integrations', '0003_auto_20210301_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify_User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('token', models.CharField(default='', max_length=2048)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('token_type', models.CharField(blank=True, max_length=10)),
                ('expires_in', models.CharField(blank=True, max_length=60)),
                ('account_name', models.CharField(default='spotify', editable=False, max_length=20)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='apiinfo',
            old_name='redirect_u',
            new_name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='api_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='scope',
            field=jsonfield.fields.JSONField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
