# Generated by Django 3.0.5 on 2021-04-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_redditapiinfo_spotifyapiinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAPIInfo',
            fields=[
                ('apiinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.ApiInfo')),
            ],
            bases=('integrations.apiinfo',),
        ),
        migrations.CreateModel(
            name='OutlookAPIInfo',
            fields=[
                ('apiinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='integrations.ApiInfo')),
            ],
            bases=('integrations.apiinfo',),
        ),
    ]
