# Generated by Django 3.2 on 2021-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_spotify_user_info_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_user_info',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outlook_user_info',
            name='connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reddit_user_info',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
