# Generated by Django 3.0.5 on 2021-03-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20210304_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify_user_info',
            name='expires_at',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
