# Generated by Django 3.0.5 on 2021-03-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_auto_20210304_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify_user_info',
            name='account_user_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
