# Generated by Django 3.0.5 on 2021-03-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210304_1421'),
        ('integrations', '0007_spotify_user_info_account_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotify_user_info',
            name='account_name',
            field=models.CharField(default='spotify', editable=False, max_length=7),
        ),
        migrations.CreateModel(
            name='Reddit_User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_user_name', models.CharField(default='', max_length=30)),
                ('user_id', models.CharField(max_length=10)),
                ('token', models.CharField(default='', max_length=2048)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('token_type', models.CharField(blank=True, max_length=10)),
                ('expires_in', models.CharField(blank=True, max_length=60)),
                ('expires_at', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(default='reddit', editable=False, max_length=6)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
