# Generated by Django 3.1.7 on 2021-03-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210304_1421'),
        ('integrations', '0008_auto_20210307_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discord_User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_user_name', models.CharField(default='', max_length=30)),
                ('user_id', models.CharField(max_length=10)),
                ('token', models.CharField(default='', max_length=2048)),
                ('refresh_token', models.CharField(blank=True, max_length=512)),
                ('token_type', models.CharField(blank=True, max_length=10)),
                ('expires_in', models.CharField(blank=True, max_length=60)),
                ('expires_at', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(default='discord', editable=False, max_length=7)),
                ('users', models.ManyToManyField(to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
